# Bundle up all the data to send over to Weatherman.
template:
  - trigger:
      platform: time_pattern
      minutes: "/15"
    action:
      - service: weather.get_forecast
        target:
          entity_id: weather.home
        data:
          type: hourly
        response_variable: weather_home_hourly
    sensor:
      - name: Weatherman Data Tag
        state: "OK"
        attributes:
          battery_strength_0000028329e608ff: >
            {% if has_value('sensor.0000028329e608ff_battery') %}
              {% if states('sensor.0000028329e608ff_battery') | int >= 90 %}
                battery-high 
              {% elif states('sensor.0000028329e608ff_battery') | int >= 60 %}
                battery-medium 
              {% elif states('sensor.0000028329e608ff_battery') | int >= 30 %}
                battery-low 
              {% else %} 
                battery-outline 
              {% endif %}
            {% else %}
              battery-off-outline
            {% endif %}
          moon_phase: >
            {% set cond_moon = state_attr('sensor.moon_phase', 'icon') %}
            {{ cond_moon.split('mdi:')[1] }}
          wm_cond_now: >
            {% set cond_now = states('weather.home') %}
            {% if cond_now == 'partlycloudy' %}{% set cond_now = 'partly-cloudy' %}{% endif %}
            {% if states('sun.sun') == 'below_horizon' %}
                {% if cond_now == 'sunny' %} night {% elif cond_now == 'partly-cloudy' %} night-partly-cloudy {% else %} {{ cond_now }} {% endif %}
            {% else %}
                {{ cond_now }}
            {% endif %}
          wm_cond_0: >
            {% set cond0 = weather_home_hourly.forecast[0].condition %}
            {% if cond0 == 'partlycloudy' %}{% set cond0 = 'partly-cloudy' %}{% endif %}
            {% set next_setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
            {% set next_rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
            {% set cond0_time = as_timestamp(weather_home_hourly.forecast[0].datetime) %}
            {% if states('sun.sun') == 'above_horizon' and cond0_time > next_setting %}
                {% if cond0 == 'sunny' %} night {% elif cond0 == 'partly-cloudy' %} night-partly-cloudy {% else %} {{ cond0 }} {% endif %}
            {% elif states('sun.sun') == 'below_horizon' and cond0_time < next_rising %}
                {% if cond0 == 'sunny' %} night {% elif cond0 == 'partly-cloudy' %} night-partly-cloudy {% else %} {{ cond0 }} {% endif %}    
            {% else %}
                {{ cond0 }}
            {% endif %}
          wm_temp_0: >
            {{ weather_home_hourly.forecast[0].temperature | round }}
          wm_time_0: >
            {{ as_timestamp(weather_home_hourly.forecast[0].datetime) | timestamp_custom('%I') | int }} {{ as_timestamp(weather_home_hourly.forecast[0].datetime) | timestamp_custom('%p') }}    
          wm_cond_1: >
            {% set cond1 = weather_home_hourly.forecast[1].condition %}
            {% if cond1 == 'partlycloudy' %}{% set cond1 = 'partly-cloudy' %}{% endif %}
            {% set next_setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
            {% set next_rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
            {% set cond1_time = as_timestamp(weather_home_hourly.forecast[1].datetime) %}
            {% if states('sun.sun') == 'above_horizon' and cond1_time > next_setting %}
                {% if cond1 == 'sunny' %} night {% elif cond1 == 'partly-cloudy' %} night-partly-cloudy {% else %} {{ cond1 }} {% endif %}
            {% elif states('sun.sun') == 'below_horizon' and cond1_time < next_rising %}
                {% if cond1 == 'sunny' %} night {% elif cond1 == 'partly-cloudy' %} night-partly-cloudy {% else %} {{ cond1 }} {% endif %}
            {% else %}
                {{ cond1 }}
            {% endif %}
          wm_temp_1: >
            {{ weather_home_hourly.forecast[1].temperature | round }}
          wm_time_1: >
            {{ as_timestamp(weather_home_hourly.forecast[1].datetime) | timestamp_custom('%I') | int }} {{ as_timestamp(weather_home_hourly.forecast[1].datetime) | timestamp_custom('%p') }}    
          wm_cond_2: >
            {% set cond2 = weather_home_hourly.forecast[2].condition %}
            {% if cond2 == 'partlycloudy' %}{% set cond2 = 'partly-cloudy' %}{% endif %}
            {% set next_setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
            {% set next_rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
            {% set cond2_time = as_timestamp(weather_home_hourly.forecast[2].datetime) %}
            {% if states('sun.sun') == 'above_horizon' and cond2_time > next_setting %}
                {% if cond2 == 'sunny' %} night {% elif cond2 == 'partly-cloudy' %} night-partly-cloudy {% else %} {{ cond2 }} {% endif %}
            {% elif states('sun.sun') == 'below_horizon' and cond2_time < next_rising %}
                {% if cond2 == 'sunny' %} night {% elif cond2 == 'partly-cloudy' %} night-partly-cloudy {% else %} {{ cond2 }} {% endif %}
            {% else %}
                {{ cond2 }}
            {% endif %}
          wm_temp_2: >
            {{ weather_home_hourly.forecast[2].temperature | round }}
          wm_time_2: >
            {{ as_timestamp(weather_home_hourly.forecast[2].datetime) | timestamp_custom('%I') | int }} {{ as_timestamp(weather_home_hourly.forecast[2].datetime) | timestamp_custom('%p') }}    
          wm_cond_3: >
            {% set cond3 = weather_home_hourly.forecast[3].condition %}
            {% if cond3 == 'partlycloudy' %}{% set cond3 = 'partly-cloudy' %}{% endif %}
            {% set next_setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
            {% set next_rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
            {% set cond3_time = as_timestamp(weather_home_hourly.forecast[3].datetime) %}
            {% if states('sun.sun') == 'above_horizon' and cond3_time > next_setting %}
                {% if cond3 == 'sunny' %} night {% elif cond3 == 'partly-cloudy' %} night-partly-cloudy {% else %} {{ cond3 }} {% endif %}
            {% elif states('sun.sun') == 'below_horizon' and cond3_time < next_rising %}
                {% if cond3 == 'sunny' %} night {% elif cond3 == 'partly-cloudy' %} night-partly-cloudy {% else %} {{ cond3 }} {% endif %}
            {% else %}
                {{ cond3 }}
            {% endif %}
          wm_temp_3: >
            {{ weather_home_hourly.forecast[3].temperature | round }}
          wm_time_3: >
            {{ as_timestamp(weather_home_hourly.forecast[3].datetime) | timestamp_custom('%I') | int }} {{ as_timestamp(weather_home_hourly.forecast[3].datetime) | timestamp_custom('%p') }}    
          wm_cond_4: >
            {% set cond4 = state_attr('weather.home', 'forecast')[0].condition %}
            {% if cond4 == 'partlycloudy' %} partly-cloudy {% else %} {{ cond4 }} {% endif %}
          wm_temp_4: >
            {{ state_attr('weather.home', 'forecast')[0].temperature | round }}
          wm_temp_4_low: >
            {{ state_attr('weather.home', 'forecast')[0].templow | round }}
          wm_time_4: >
            {{ "%s" % (["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][as_timestamp(state_attr('weather.home', 'forecast')[0].datetime) | timestamp_custom('%w') | int]) }}
          wm_cond_5: >
            {% set cond5 = state_attr('weather.home', 'forecast')[1].condition %}
            {% if cond5 == 'partlycloudy' %} partly-cloudy {% else %} {{ cond5 }} {% endif %}
          wm_temp_5: >
            {{ state_attr('weather.home', 'forecast')[1].temperature | round }}
          wm_temp_5_low: >
            {{ state_attr('weather.home', 'forecast')[1].templow | round }}
          wm_time_5: >
            {{ "%s" % (["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][as_timestamp(state_attr('weather.home', 'forecast')[1].datetime) | timestamp_custom('%w') | int]) }}
          wm_cond_6: >
            {% set cond6 = state_attr('weather.home', 'forecast')[2].condition %}
            {% if cond6 == 'partlycloudy' %} partly-cloudy {% else %} {{ cond6 }} {% endif %}
          wm_temp_6: >
            {{ state_attr('weather.home', 'forecast')[2].temperature | round }}
          wm_temp_6_low: >
            {{ state_attr('weather.home', 'forecast')[2].templow | round }}
          wm_time_6: >
            {{ "%s" % (["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][as_timestamp(state_attr('weather.home', 'forecast')[2].datetime) | timestamp_custom('%w') | int]) }}  
          wm_cond_7: >
            {% set cond7 = state_attr('weather.home', 'forecast')[3].condition %}
            {% if cond7 == 'partlycloudy' %} partly-cloudy {% else %} {{ cond7 }} {% endif %}
          wm_temp_7: >
            {{ state_attr('weather.home', 'forecast')[3].temperature | round }}
          wm_temp_7_low: >
            {{ state_attr('weather.home', 'forecast')[3].templow | round }}    
          wm_time_7: >
            {{ "%s" % (["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][as_timestamp(state_attr('weather.home', 'forecast')[3].datetime) | timestamp_custom('%w') | int]) }}       
